---

- name: Create miniconda installer tempfile
  ansible.builtin.tempfile:
    prefix: ansible-miniconda-installer.
    suffix: .sh
  register: miniconda_installer_tempfile

- name: Collect miniconda installer
  ansible.builtin.get_url:
    url: "https://repo.anaconda.com/miniconda/{{ miniconda_installer }}"
    dest: "{{ miniconda_installer_tempfile.path }}"
    force: true
    mode: "0755"

- name: Miniconda installer block
  block:

    - name: Run miniconda installer
      ansible.builtin.command: "{{ miniconda_installer_shell }} {{ miniconda_installer_tempfile.path }} -b -p {{ miniconda_prefix }}"
      register: __miniforge_install
      changed_when: __miniforge_install.rc != 0

  always:

    - name: Remove minicoda installer
      ansible.builtin.file:
        path: "{{ miniconda_installer_tempfile.path }}"
        state: absent
