---

- name: Update miniforge version (exact)
  ansible.builtin.command: >-
    {{ miniforge_prefix }}/bin/mamba install --yes
    {{ '--override-channels --channel' if miniforge_channels else '' }}
    {{ miniforge_channels | join(' --channel ') }}
    conda={{ miniforge_version }}
  when: miniforge_version != 'latest' and (miniforge_installed_version.stdout.split() | last) != miniforge_version
  register: __miniforge_update
  changed_when: __miniforge_update.rc != 0

- name: Update miniforge version (latest)
  ansible.builtin.command: >-
    {{ miniforge_prefix }}/bin/mamba update --yes
    {{ '--override-channels --channel' if miniforge_channels else '' }}
    {{ miniforge_channels | join(' --channel ') }}
    conda
  register: __miniforge_update
  changed_when: "'All requested packages already installed' not in __miniforge_update.stdout"
  when: miniforge_version == 'latest'
